version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: cd demo
      timeout: 300
      runas: root
  ApplicationStop:
    - location: cd demo
      timeout: 300
      runas: root
